#!/bin/bash
#
# Clear the shell
clear
# Create new docker volume
read -p "Enter the name you want to assign to the new docker volume: " new_volume
docker volume create $new_volume
echo ""; echo ""
#
# Sets the value directory
read -p "Enter the directory in which the file to restore is placed: " directory
echo ""; echo ""
#
# Sets the value backup_file
echo "LIST OF BACKUPS"; echo ""
ls -l /backups/autobackup | grep -vi total | awk '{print $9}'
echo ""
read -p "Enter the complete name of the backup tar.gz file you are trying to restore: " backup_file
echo ""; echo ""
#
# Deletes old nohup in current directory
rm -f nohup.out
#
# Start restore
nohup docker run --rm -v "$new_volume":/data -v "$directory":/backup busybox tar xzf /backup/"$backup_file" -C /data
echo ""; echo ""
#
# Warning the user
echo "You can now close this shell\nPlease open another session"
# Deletes new nohup in current directory
rm -f nohup.out
